### ISSUE TITLE
World name with a space character

### ISSUE THREAD

**Issue by CoverOpe** [endercrest/VoidSpawn#10]
Edit by Thomas: Check if command supports for worlds with space character.

Running a bukkit server on 1.10.2.

Everytime we hop into the void after using "/voidspawn set" we just die.  
In addition, voidspawn is not recognizing the world as a valid world so I can't change the mode either.  In the worlds config we get : http://puu.sh/rNTaT/281af63855.png : so it appears that it is using the correct world, but for some reason I just die every single time.  I have tried it without OP and without the group with the '*' permission.  I have also tried giving that group the "- -vs.override" node but it still appears to just plain not work.  

Absolutely any ideas?  I might just be going crazy and forgetting something simple.  

I appreciate any response seeing as literally no one else has had this issue.

Thanks!

**Comment by endercrest** [comment]
@CoverOpe Hmm, my guess is it is failing because the name has a space. Have you tried to throw "" around the world name?

I am not actively developing on this plugin so I am not sure what the status of it is with current builds.

**Comment by CoverOpe** [comment]
Yeah even with the quotes it just pings as in invalid world.  I've checked multiverse and there's no variation of the name that will actually work with it.  I can't even fathom why I'm having this issue lol.

**Comment by endercrest** [comment]
When using the commands, do you receive an error?

**Comment by CoverOpe** [comment]
There isn't an error on the console or the game, just says it's in invalid world.

**Comment by endercrest** [comment]
Also, what is the command that you are using when setting the mode.

**Comment by CoverOpe** [comment]
/voidspawn mode Spawn "The Nexus" (or variations of that name)

**Comment by endercrest** [comment]
And in which world are you setting it in?

**Comment by endercrest** [comment]
So you could try going into "The Nexus" then typing just "/vs mode Spawn".

**Comment by CoverOpe** [comment]
I'm actively in The Nexus world which is NOT the default world.  I thought that might have been the case but I saw that the plugin worked on multiple worlds so I wasn't sure if that would have been the cause.

Also unfortunately we have Voxel Sniper so /vs will cue voxel, but I'll try it with /voidspawn real fast.

**Comment by CoverOpe** [comment]
And that seems to have fixed it!  Haha, derp.  Thanks for the help endercrest!

**Comment by endercrest** [comment]
Great, my guess is I forgot to support in the command the ability to have a space in the name.

**Comment by CoverOpe** [comment]
Everything seems to work great besides that!  Thanks for the great plugin.  It helps a lot since we have a whooole lot of places where you can fall off ;)

**Comment by endercrest** [comment]
No problem. :)

I am not sure when or if I will patch this bug. As I am not currently super active in the Minecraft community anymore. If I find some free time, I might take a look again and see if I will patch it.

**Comment by CoverOpe** [comment]
It's not too big of a bug.  As long as people can just work around it by being actively in the world it shouldn't be a problem.  Real life comes first!

**Comment by endercrest** [comment]
I am going to leave this issue open to remind me and I will hopefully one day patch it. 😛 Thanks for the report.

**Comment by CoverOpe** [comment]
No worries! Have a good one.

**Comment by endercrest** [comment]
@CoverOpe Just so you have an update, this has been fixed in the source code. I will be posting a snapshot with it really soon. I might even be pushing a full release soon.

**Comment by endercrest** [comment]
Officially fixed in V1.12.0
