### ISSUE TITLE
Teleport Damage Option

### ISSUE THREAD

**Issue by PieCreeper12** [endercrest/VoidSpawn#100]
My suggestion is to add an option to make the player take a configurable amount of damage when teleporting out of the void. This would be useful for the infinite fall mode. If the player falls under a floating island, they would land back on top of it. However, if they fall while under nothing, they would take damage then die rather than infinitely fall.

**Comment by endercrest** [comment]
Hey! This is already supported by VoidSpawn. This can be done via `/vs option set damage <amount>`.
