### ISSUE TITLE
I need help setting up the plugin.

### ISSUE THREAD

**Issue by real-vgi** [endercrest/VoidSpawn#106]
Hello, I'm running AOneblock and I need this plugin to stop my users from falling into the void.
VoidSpawn doesn't seem to work out of the box (when I fall in the void it doesn't do anything.)

Could you please help me configure it? As the configuration doesn't have many lines and Its verry confusing for me.

**Comment by endercrest** [comment]
There is a chance you were running into a problem where VoidSpawn wasn't working properly with the latest versions of Bentobox (w/ AOneBlock addon). This has since been fixed and will be available in 1.21.0 of VoidSpawn.
