### ISSUE TITLE
Death still wins

### ISSUE THREAD

**Issue by SlimeDog** [endercrest/VoidSpawn#12]
Environment: _Spigot_ 1.10.2, _VoidSpawn_ 1.11.0, and the usual collection of _WE/WG/MV/PEX/etc_., all latest pulls.

I configured _askyblock_ to _allowfallingteleport:true_. I configured _-vs.override_ in _PEX_. I configured _VoidSpawn_ for command mode to send the player to a safe location (in a different world) via mvtp. When he jumps over the edge of the island, the player is teleported to the safe location. But when the player goes back to the island, he dies. Since the point of _VoidSpawn_ is to avoid death, I need help. What more information would be helpful?

At least one other person has reported this behavior on [MS-Spigot](https://www.spigotmc.org/threads/voidspawn.127604/page-9999).

**Comment by endercrest** [comment]
Thanks for the report, I will take a look at this. I believe I have identified the problem.

**Comment by SlimeDog** [comment]
Thanks. Observed expected behavior in one non-island world.

**Comment by endercrest** [comment]
Are you only running into this problem with command based teleports?

**Comment by SlimeDog** [comment]
Here is a sample of my worlds.yml:
`world:
  mode: command
  command: mvtp e:world_void:0.5,64,0.1:0:0`

All worlds share the same configuration. For the ASkyBlock world, death ensues on return. For one "normal" world tested, not.

**Comment by endercrest** [comment]
Thanks, while testing didn't even realise a command was never add to register a command.

**Comment by endercrest** [comment]
@SlimeDog https://github.com/endercrest/VoidSpawn/releases/tag/V1.11.1-SNAPSHOT

This is a pre-release that contains a fix for this bug. Should you want an immediate fix, that release should do. Nothing else has changed in it.

**Comment by endercrest** [comment]
I will close this issue once I push an official version to spigot and bukkit.

**Comment by SlimeDog** [comment]
Thanks. Yeah, I just edit the worlds file. While you're in there, any chance for multiple command support?

**Comment by endercrest** [comment]
Ya, I will throw that in quickly.

**Comment by endercrest** [comment]
@SlimeDog https://github.com/endercrest/VoidSpawn/releases/tag/V1.11.2-SNAPSHOT

**Comment by SlimeDog** [comment]
Verified that 1.11.2-SNAPSHOT resolves the island death issue.
