### ISSUE TITLE
Player's Dying On Teleport

### ISSUE THREAD

**Issue by MeddlingMoose** [endercrest/VoidSpawn#2]
Hi there, I have the VoidSpawn V1.8.0 which works, though once the players teleport and hit the ground they seem to die... Is there something I'm missing? :P 

Thanks,
Moose

**Comment by endercrest** [comment]
Thanks for the report. I will take a look into this in the next few days.

**Comment by endercrest** [comment]
After doing some testing everything things seems to work. If you are using permissions that give you all permission make sure to negate vs.override. An example of doing this for pex would be:

/pex group add -vs.override

Other than that it seems to work fine.

**Comment by MeddlingMoose** [comment]
Of course.

Craftbukkit git-Spigot-3ccbe77-a6a57a9 (MC: 1.8.7)
VoidSpawn is Version 1.8.0

Not quite sure what other information I can give you other than players will jump off spawn island, be teleported back to spawn and die on impact. If a player is using fly than they survive.
