### ISSUE TITLE
ProtocolSupport support

### ISSUE THREAD

**Issue by Dodikabird** [endercrest/VoidSpawn#20]
I just installed ProtocolSupport, and the actual detection wether you're in the void or not simply ceases function. You won't even get a message, it just won't work.

**Comment by endercrest** [comment]
Thanks for the report, I will take a look at it tomorrow.

**Comment by endercrest** [comment]
@Dodikabird I have still not found or been able to recreate this error. Are you sure ProtocolSupport is causing this?

**Comment by endercrest** [comment]
Closing, will reopen if a response is provided.
