### ISSUE TITLE
Problem with ASkyBlock possible solutions.

### ISSUE THREAD

**Issue by Ancard** [endercrest/VoidSpawn#22]
Well, I have a problem with skyblock, it is not an error but it could be considered an improvement.
When you fall out of the skyblock, voidspawn should remove the objects or make some kind of penalty, if not, you never feel the adrenalin of being at the edge of danger.
The ways in which it would be interesting to solve this:
1) Add the default option to island mode so that you delete objects from the inventory when you fall into the void.
2) Add the possibility of having a file where you can set the list of commands that you want to run when falling into the void. As well as allowing you to choose the option of being able to return to the spawn or to the last point in the land that you touched before falling.

edit: You could also add a radio that has the spawn center and where voidspawn is effective, and that leaving that radius is no longer effective and fall and die as always.

**Comment by endercrest** [comment]
Thanks for the suggestions, I will take these into consideration when adding a new update.

**Comment by endercrest** [comment]
Option 1 will for sure be available 1.13.

**Comment by endercrest** [comment]
Hybrid mode has now been implemented.
