### ISSUE TITLE
It isnt working?

### ISSUE THREAD

**Issue by ErayChumak** [endercrest/VoidSpawn#23]
So I have alt account which I use for testing and when I die (Jump of the spawn which is in the void) it kills him instead of teleporting him to /spawn.

How do I fix this problem?

Is there any permission node I have to add to the rank for it to work or?

**Comment by endercrest** [comment]
There is a permission node vs.override so if the player is given all permissions, you will have to negate it ("-vs.override"). If that doesn't fix the problem let me know.

**Comment by ErayChumak** [comment]
Wait nevermind, I realized that I had to set the mode for the world and also set the actual spawn point.

Sorry for bothering you.

**Comment by endercrest** [comment]
No worries. :) Have a good one!

**Comment by ErayChumak** [comment]
Thanks, you too :D
