### ISSUE TITLE
Dying from fall damage

### ISSUE THREAD

**Issue by NinjaSlatz** [endercrest/VoidSpawn#29]
I do (/vs mode island) in my Island world, when players jump into the void, they are teleported to their island home but die from fall damage. I am using aSkyBlock 3.0.5.4, and the latest version of VoidSpawn, I've tried with earlier versions, but still have the same issue. Thanks.

**Comment by NinjaSlatz** [comment]
@endercrest 
ASkyBlock v3.0.5.4
AuctionHouse v1.4.5
AutoMessage v1.1
BetterBlockBreaking v6.6.0_1.10.2
boosCooldowns v3.8.6
BottledExp v2.2.3.0
BuycraftX v0.1.3-SNAPSHOT
CapsLock v1.0.4
ChatReaction v1.6.2
ChestShop v3.8.12
ChopTree3 v4.0.0
ClearChat v3.0.0
ClearLag v2.9.3
CompatNoCheatPlus v6.6.3-SNAPSHOT-sMD5NET-b87
CoreProtect v2.13.2
CrazyCrates v1.6.3.4
CustomTime v1.3.3
CustomUknownCommand v1.3.3.7
DeathMessages v1.11.0
EchoPet v1.0.4-SNAPSHOT-b29
EpicRename v2.6.2
Essentials v2.0.1-b468
EssentialsChat v2.0.1-b468
EssentialsProtect v2.0.1-b468
EssentialsSpawn v2.0.1-b468
eZProtector v4.1.5
FastAsyncWorldEdit v17.02.26-74baf5f-531-10.8.31
FeatherBoard v3.12.0
Firework v0.2
ForcedGrammar v1.8.1
GAListener v1.3.2
Harvest v1.2
Heads v1.6.3
HelpPages v1.0
HolographicDisplays v2.2.2
Interactables v1.1.2
KillsPlus v2.3
KitAdder v2.6
KitPreview v4.2.4
LeaderHeads v2.7.2
LibsDisguises v9.0.9
mcMMO v1.5.07-SNAPSHOT
mcMMOAction v1.2.2
MineResetLite v0.4.6
MineResetLitePlus v2.5.0
MobsDropHeads v1.7.2
Multiverse-Core v2.5-b719
NoCheatPlus v3.15.0-SNAPSHOT-sMD5NET-b1043
PermissionsEx v1.23.4
PlayerVaults v3.5.6-b181
PlugMan v2.1.1
PortalCommands v2.1.2
PotionStacker v1
ProtocolLib v4.2.0
ProtocolSupport v4.24
PvPManager v3.3.3.2
Rules v1.5
ShopGUIPlus v1.4.12
ShowCaseStandalone v781
SilkSpawners v3.8-SNAPSHOT-b378
SimpleAlias v1.6.2
SimpleTrading v1.3
SketchMap v1.0.0
SkyWars v2.2.0
SuperTrails v9.6.4
Tablist v1.3.1.11
TrainingPvP v7.4
Vault v1.5.6-b49
ViaVersion v1.0.4
VoidSpawn v1.10.0
VoteParty v1.4.1
Votifier v1.9
WarpPortals v5.6.3
WGBlockRestricter v1.0
WGCustomFlags v1.0
WhatIsIt v1.3.9
WhoseOnline v1.0
WorldEdit v6.1.3;7a097ca
WorldGuard v6.1.2;e38d98d with custom flags plugin.
WorldGuard_FlyStop v1.0

**Comment by endercrest** [comment]
It looks like you are running VoidSpawn v1.10.0, I would recommend updating to v1.14.0 and letting me know if the problem persists as the island mode has gotten a fairly large rewrite in the most recent version.

**Comment by NinjaSlatz** [comment]
I don't know if you read the post or not, but I said  that I am "using the latest version of VoidSpawn, I've tried with earlier versions, but still have the same issue."

In other words, I am running VoidSpawn v1.10.0 to see if that would solve my problem.

**Comment by endercrest** [comment]
@NinjaSlatz Ok, thanks for clearing that up. I will have to look into the problem some more as I am not sure what is causing the problem.

**Comment by endercrest** [comment]
@NinjaSlatz By any chance could you try VoidSpawn without protocol lib and see if that fixes the problem? I have had a report with a protocol lib conflict but have not been able to recreate it.

**Comment by NinjaSlatz** [comment]
I don't know what happened but the problem is fixed.

**Comment by endercrest** [comment]
Hmm, that is odd...
