### ISSUE TITLE
Minecraft 1.8.7

### ISSUE THREAD

**Issue by wilsondc15** [endercrest/VoidSpawn#3]
This plugin's functions do not work on Bukkit 1.8.7. The /vs command does however, show all the info and messages when you do a command, but no matter your setting, you die in the void normally as if the plugin is not even installed.

**Comment by endercrest** [comment]
I am aware of this and taking a look into this today.

**Comment by endercrest** [comment]
After doing some testing everything things seems to work. If you are using permissions that give you all permission make sure to negate vs.override. An example of doing this for pex would be:

/pex group <group> add -vs.override

Other than that it seems to work fine.
