### ISSUE TITLE
Add sound while teleport

### ISSUE THREAD

**Issue by LemonLight** [endercrest/VoidSpawn#34]
Hi :) 

Thanks for you great plugin ! I have got a suggestion. Can you add the ability to add a sound when players are teleport ? (i.e. block.note.pling) 

Thanks !

**Comment by endercrest** [comment]
Thanks for the suggestion! I will look into adding support for this. :)

**Comment by endercrest** [comment]
Just wanted to let you know that this has now been added one V1.16.1. Thanks for the feedback and let me know if you have any other requests.
