### ISSUE TITLE
Slab with height Y:0.5 tp's you to spawn

### ISSUE THREAD

**Issue by FrankHeijden** [endercrest/VoidSpawn#35]
Title says it all,

When you place a slab on the lowest place possible and you walk over it, you get immediately teleported to spawn.

Frank

**Comment by endercrest** [comment]
You can change the offset or where the detection zone is by using /vs offset. I recommend playing around with it till you find a value that you like. It accepts both positive and negative values. Also if I remember correctly, positive values shift the offset down, and negative shift it up.
