### ISSUE TITLE
Message Error

### ISSUE THREAD

**Issue by CyprusDesigns** [endercrest/VoidSpawn#36]
http://cypruso.me/i/a2f9b.png

Seems to give that to everyone that falls into the void, config doesn't seem to show what "commands" are ran, server is 1.8.8.
I also cleared /vs message so no idea what's going on.

**Comment by endercrest** [comment]
Could you post your Worlds.yml? That should help track down the problem.

**Comment by endercrest** [comment]
Closing, will reopen if a response is provided.
