### ISSUE TITLE
Mode Island not working for me

### ISSUE THREAD

**Issue by Tomcatchriss** [endercrest/VoidSpawn#4]
Hello, your plugin working fine in mode spawn, but we're using askyblock and want to teleport to the player island. Your plugin only support IslandWorlds. Can you make an update, so it will supports the mode Island also for ASkyblock?

**Comment by endercrest** [comment]
I can definitely look into implementing this.

**Comment by endercrest** [comment]
ASkyblock is now supported as of V1.10.0. Please let me know if you run into any issues.

https://www.spigotmc.org/resources/voidspawn.19350/update?update=92165
