### ISSUE TITLE
How to teleport players?

### ISSUE THREAD

**Issue by BenjaminHoegh** [endercrest/VoidSpawn#41]
How do you teleport players? when using Spigot and multiverse ?

**Comment by endercrest** [comment]
@BenjaminHoegh If you want to have cross world you need to specify world names. Let set up an example where there are two worlds, WorldA and WorldB.

Say if we enter the void in WorldA, then we want to go to a point in WorldB. First thing we need to set the mode for WorldA. So using the command `/vs mode spawn WorldA`. Following that, we will want to set the spawn location, going to where you want it in WorldB and  use the command `/vs set WorldA`. This sets the spawn point for when entering the void in WorldA.

Hopefully this helps clear things up. Please let me know if you have any other questions. 😃

**Comment by BenjaminHoegh** [comment]
that's how you set spawn yes, but how to teleport to the world where you build your house instead of been teleportet to spawn ?

**Comment by endercrest** [comment]
You could try using command mode, how would a player normally get to their home via a command?

**Comment by endercrest** [comment]
@BenjaminHoegh Need a bit more context of how you define a "home". Is a home a location a player sets? Not entirely sure what you are requesting.

**Comment by endercrest** [comment]
Closing, will reopen if a response is provided.
