### ISSUE TITLE
vs.enable permission checked continuously

### ISSUE THREAD

**Issue by SlimeDog** [endercrest/VoidSpawn#42]
Spigot 1.13 latest
VoidSpawn 1.17.0

While moving up or down through water (or "bobbing" on the surface), the _vs.enable_ permission is checked every tick. The ocean floor is at Y=46 in the test scenario, nowhere near Y<0. This seems unnecessary.

**Comment by SlimeDog** [comment]
vs.enable also seems to be checked continuously when the player is not in water, just moving around on any surface.

**Comment by SlimeDog** [comment]
It is not clear why the permissions need to be checked at all until a player passes into the void.

**Comment by endercrest** [comment]
Ya, that is an error on my part. Happened when I did a small refactor.
