### ISSUE TITLE
SuperiorSkyblock Support

### ISSUE THREAD

**Issue by PlinioRasch** [endercrest/VoidSpawn#50]
I'd really appreciate if you added support for this plugin, it's currently the top purchased resource on mc-market and recently added on spigot but growing fast on spigot too.

https://www.spigotmc.org/resources/%E2%AD%90%EF%B8%8F-superiorskyblock2-%E2%AD%90%EF%B8%8F-brand-new-core.63905/

https://www.mc-market.org/resources/8089/update?update=23121

**Comment by endercrest** [comment]
I will link into integrating with this plugin. Current trouble is this is a premium plugin which means I can't get a copy of the source and it looks like they don't have any public API to interface with.

**Comment by endercrest** [comment]
Now available in [v1.19.0](https://github.com/endercrest/VoidSpawn/releases/tag/V1.19.0)
