### ISSUE TITLE
Unable to return to spawn point after death

### ISSUE THREAD

**Issue by SlimeDog** [endercrest/VoidSpawn#53]
Spigot 1.13.2
VoidSpawn 1.18.0-SNAPSHOT

**Describe the bug**
My new parkour world contains the equivalent of command blocks to set spawn points as the player progresses along the parkour track. When a player falls, I would like them to die, then return to the spawn point (even better alternative: return to the last touch point). But in either case, I want to record (and report) a death. I have tried several different VoidSpawn configurations -- mode:touch, mode:command, hybrid:true -- but I have not been able to achieve the desired result. I can get either touch or kill, but not both. Please advise.

**Comment by endercrest** [comment]
The next release will be exposing 4 new variables: player.touch.x, player.touch.y, player.touch.z, player.touch.world. This will hopefully allow for half of what you are wanting.

The second half would be addressed by #64. Going to close off this issue.
