### ISSUE TITLE
Early Teleportation

### ISSUE THREAD

**Issue by LE0ZY** [endercrest/VoidSpawn#54]
**Describe the bug**
The plugin teleports player too early at y=0.
This prevents players with /fly to place the first block at y=0

**To Reproduce**
1. Set the plugin up
2. Fly to y=1
3. Slowly fly to y=0
4. Instant Teleportation

**Expected behavior**
A configuration of at which y level should the detector fire

**Screenshots**

**VoidSpawn Version:** Latest
**MC Version:** Paper 1.12.2
**Spigot Version:** 1.12.2

**Additional context**

**Comment by endercrest** [comment]
@LE0ZY Hey! You can use the command `/vs offset` to set the vertical offset. Let me know if you run into any other problems.
