### ISSUE TITLE
Glitching into the island

### ISSUE THREAD

**Issue by JHarris12345** [endercrest/VoidSpawn#56]
**Describe the bug**
After a while of standing doing nothing or minimal movement, you start glitching into the island and have to /spawn then /is or relog. This only happens on a 1.14 client with a 1.13.2 server and 1.14.4 bungee

**To Reproduce**
1. Log into a 1.14 client on a 1.13.2 server (possibly the 1.14.4 bungee is needed)
2. Create an island and then go in /gmc and just hover close to the ground and do nothing for a while. Maybe just leave the screen open. After a bit, usually 2 - 5 minutes, if you try and land, you will glitch into the ground. I reckon you can do the same by standing on the ground for a while but flying works better for me to make the glitch. If you put a few animals on the island its easier to know if you are glitched because they stop moving

**Expected behavior**
You dont glitch

**Screenshots**
N/A for now will post next time I glitch but it isnt vital

**VoidSpawn Version:** V 1.18.1
**MC Version:** 1.14.4
**Spigot Version:** 1.13.2

**Comment by endercrest** [comment]
@JHarris12345 What skyblock plugin and skyblock version are you using? Would you be able to grab a video of this problem?

**Comment by endercrest** [comment]
Closing this off will reopen if you have a video.
