### ISSUE TITLE
You can dupe items with the extra mob drops upgrade

### ISSUE THREAD

**Issue by JHarris12345** [endercrest/VoidSpawn#57]
**Describe the bug**
You can dupe items by mobs picking up dropped items and killing them for double drops

**To Reproduce**
1. Go to skyblock and upgrade your mob drops so you get 2x drops etc
2. Drop a sword on the ground and let a zombie pick it up
3. Kill the zombie and you get 2 (or more) of the sword

**Expected behavior**
Killing mobs shouldnt multiply the drops if they are picked up

**MC Version:** 1.14.4
**Spigot Version:**1.13.2

**Comment by endercrest** [comment]
@JHarris12345 Hey, this sounds like a problem with your skyblock plugin. VoidSpawn doesn't make any modifications to mob drops.
