### ISSUE TITLE
How to use '/ vs command' to set the command to fall into the void

### ISSUE THREAD

**Issue by Kaitouhan** [endercrest/VoidSpawn#59]
world:
  spawn:
    x: 58.358957082543185
    y: 105.0
    z: -118.69834622633556
    pitch: -1.1997869
    yaw: -178.98401
    world: ZC
  mode: spawn
  message: ''
  sound:
    name: UI_TOAST_CHALLENGE_COMPLETE
    volume: 1.0
  **command: '/effect give @p minecraft:slowness 500 1 '**

**Comment by endercrest** [comment]
Hey, VoidSpawn uses a slightly different placeholder than default MC.

That command you will want is `effect give ${player.name} minecraft:slowness 500 1`

**Comment by Kaitouhan** [comment]
ty




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Thomas Cordua-von Specht"<notifications@github.com&gt;; 
发送时间: 2020年2月28日(星期五) 凌晨0:22
收件人: "endercrest/VoidSpawn"<VoidSpawn@noreply.github.com&gt;; 
抄送: "691767737"<691767737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [endercrest/VoidSpawn] How to use &#39;/ vs command&#39; to set the command to fall into the void (#59)




Hey, VoidSpawn uses a slightly different placeholder than default MC.
 
That command you will want is effect give ${player.name} minecraft:slowness 500 1
