### ISSUE TITLE
VoidSpawn Error

### ISSUE THREAD

**Issue by MilkLegend** [endercrest/VoidSpawn#60]
**Describe the bug**
VoidSpawn works smoothly, its just it spams my console with an error.

**To Reproduce**
1. Put VoidSpawn on a server on 1.12.2 PaperMC

**Expected behavior**
No errors, expected it to not spam my console.

**Screenshots**
https://mcpaste.io/0a46a0206f266553

**VoidSpawn Version: 1.18.2
**MC Version:** 1.8.9
**Spigot Version:** 1.12.2 PaperMC Latest

**Comment by endercrest** [comment]
Hey, VoidSpawn 1.18.2 only officially supports 1.13 and above. This error is being caused by a 1.13 API not existing in your server. 

You can download v1.16.1 for your server. Note that no support will be provided for it.
Download it from https://dev.bukkit.org/projects/voidspawn/files/2431995
