### ISSUE TITLE
Island Mode 1.15.2 / BentoBox

### ISSUE THREAD

**Issue by LavRad** [endercrest/VoidSpawn#62]
https://hasteb.in/xudahoku.rb

**Describe the bug**
Island Mode does not work on 1.15.2 with the latest BentoBox update.

**To Reproduce**
Fall in the void while using Island mode, this error will spam and the user will die.

**Expected behavior**
User to teleport to island.
Island mode does not work, however Spawn mode does work.
I expect this is some sort of impact of a BentoBox update (I am running latest).

**VoidSpawn Version:** 1.18.2
**MC Version:** 1.15.2
**Spigot Version:** 1.15.2

**Comment by endercrest** [comment]
Thanks for the report! Will look into getting this patched in the next few days.

**Comment by LavRad** [comment]
Any news on this? Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by endercrest** [comment]
I have fixed this bug in https://github.com/endercrest/VoidSpawn/commit/c92b78766cbf0abc4085f7e1a6561591fe5038b2. I am hoping to get an official release out in the next few days. Aiming to include an additional feature or two before releasing it.

**Comment by LavRad** [comment]
Could it be released without the additional features? Or do you have an estimate of when this is going to be part of the update?

**Comment by endercrest** [comment]
This is available in v1.18.3. You can download it [here](https://github.com/endercrest/VoidSpawn/releases/tag/V1.18.3). It will be available on SpigotMC in the next day or so.
