### ISSUE TITLE
Could not pass event PlayerMoveEvent to VoidSpawn v1.18.3 

### ISSUE THREAD

**Issue by trickdecisionz** [endercrest/VoidSpawn#67]
im getting a constant spamming error from the voidspawn

https://pastebin.com/eAu3aCR0

it stops me from reading my console now

**Comment by endercrest** [comment]
Looks like you are running an unsupported version of Spigot. v1.18.3 only supports MC 1.13 and above. v1.16.1 was the last version that supports older versions. That can be downloaded from https://www.spigotmc.org/resources/voidspawn.19350/update?update=167379
