### ISSUE TITLE
Newbie here, don't know how to set up the plugin

### ISSUE THREAD

**Issue by Sippytea** [endercrest/VoidSpawn#83]
I gave myself the vc.* permission to true; and then in-game I did the command /vs mode Touch <world name>

I jumped into the void to test it but I just die like usual. 

The documentation is confusing and my friends already died yesterday because I didn't know how to configure the bot correctly; any help would be appreciated.

**Comment by endercrest** [comment]
Hey @Sippytea,

Could you provide some additional info like what version of MC you are using and which version of VoidSpawn you are using? A useful command is `/vs info` which should provide additional info on your setup. Could you also share the output of that? Thanks!

**Comment by Sippytea** [comment]
So sorry for opening a ticket, I ended up figuring things out! I put the world name instead of the world name with the_end, so that's why it wasn't working ^-^

Thank you for your time!
