### ISSUE TITLE
Bentobox AOneblock not respawning, throw errors

### ISSUE THREAD

**Issue by Croyd** [endercrest/VoidSpawn#85]
Doesn't work with Bentobox AOneblock

Jump off island and die instead of respawn.
The log fills with move errors.

Lateset version of VoidSpawn
Minecraft 1.16.5
Papaer 1.16.5

Here is the link to a paste bin of error: https://pastebin.com/y6FgUmiG

**Comment by endercrest** [comment]
Hey @Croyd, this is due to a change in Bentobox's API. This is fixed in #82, which I will hopefully get an update out soon.

**Comment by endercrest** [comment]
Fixed in V1.19.3
