### ISSUE TITLE
Players still dying on respawn

### ISSUE THREAD

**Issue by crazzygammer126** [endercrest/VoidSpawn#90]
Hey, So ive set the spawn for where the players should respawn. When players jump into the void they teleport back to where they should. However, Players often die when they have teleported back. They "Fall from a high place". This happens in survival mode. Is there a setting to disable this or is this an issue. Could you please get back to as soon as possible.

EDIT: Upon furhter testing i realised this is happening when users hold down CTRL + W whilst falling into the void. Is there a fix to this as i would not like my players dying.

**Comment by elmaslarry** [comment]
Same issue

**Comment by endercrest** [comment]
This issue should be fixed in v1.19.5. Please let me know if you still find other scenarios where you are dying. Thanks!
