### ISSUE TITLE
issue using mohist

### ISSUE THREAD

**Issue by VovelPunch** [endercrest/VoidSpawn#97]
[ERROR]: 
Could not load 'plugins/VoidSpawn.jar' in folder 'plugins' 
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.18

mohistversion #886

**Comment by LukeAtomic** [comment]
Your not using the latest version of Minecraft. For 1.18 and below you will need to download the older version. https://www.spigotmc.org/resources/voidspawn.19350/history.

**Comment by VovelPunch** [comment]
thanks
