### ISSUE TITLE
pls update

### ISSUE THREAD

**Issue by DimaSergeew** [endercrest/VoidSpawn#99]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**VoidSpawn Version:**
**MC Version:**
**Spigot Version:**

**Additional context**

**Comment by KahpotVanilla** [comment]
> What's the issue????

I think this guy just tell you to update the resource to the latest version of Minecraft

**Comment by AdamAtomus** [comment]
Just tested it on 1.18.2 and 1.19, and it works completely fine.

**Comment by endercrest** [comment]
Hey! Current version of VoidSpawn should work, but I am in the process of updating the plugin. Closing this issue off 😄
